<?php
/**
 * Blocklane — asset loading and performance filters.
 *
 * Front-end color-ramp + print stylesheets, on-demand per-block variation
 * CSS, core block CSS split, and WP legacy emoji polyfill removal. All
 * asset / byte-on-the-wire concerns live here. Fonts are self-hosted via
 * theme.json fontFace declarations — a family downloads only when text
 * actually uses it, so there is no font enqueue and no CDN dependency.
 *
 * @package blocklane
 * @since   0.3.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Enqueue the color-ramp layer and the print stylesheet.
 *
 * color-ramps.css is generated by tools/build-color-ramps.mjs from
 * assets/design-tokens/ramps.json: the under-the-hood gray/status ramps and
 * the primary/secondary/accent ramps derived live (color-mix) from the
 * theme.json palette roles. The palette stays at 8 picker swatches; this
 * file carries the ~90 ramp steps pattern markup binds to.
 *
 * @since 0.1.0
 * @return void
 */
function blocklane_enqueue_assets() {
	wp_enqueue_style(
		'blocklane-color-ramps',
		get_theme_file_uri( 'assets/css/color-ramps.css' ),
		array(),
		BLOCKLANE_VERSION
	);

	wp_enqueue_style(
		'blocklane-print',
		get_theme_file_uri( 'assets/css/print.css' ),
		array(),
		BLOCKLANE_VERSION,
		'print'
	);
}
add_action( 'wp_enqueue_scripts', 'blocklane_enqueue_assets' );

/**
 * Editor-only script: prunes core block styles that bypass the theme's
 * token system (see assets/js/editor.js).
 *
 * @since 0.5.0
 * @return void
 */
function blocklane_enqueue_editor_assets(): void {
	wp_enqueue_script(
		'blocklane-editor',
		get_theme_file_uri( 'assets/js/editor.js' ),
		array( 'wp-blocks', 'wp-dom-ready', 'wp-hooks' ),
		BLOCKLANE_VERSION,
		true
	);
}
add_action( 'enqueue_block_editor_assets', 'blocklane_enqueue_editor_assets' );

/**
 * Enqueue per-block CSS files on demand.
 *
 * Scans `assets/styles/` for files matching `core-<block>.css` (e.g.,
 * `core-navigation.css`, `core-cover.css`) and registers each one with
 * `wp_enqueue_block_style()` using the `path` argument so WordPress only
 * injects the stylesheet when the corresponding block actually renders
 * on the page (WP 6.4+). Drop a new file in `assets/styles/` and it
 * loads automatically — no PHP edit required.
 *
 * Filename convention:
 *   `core-<block>.css`  →  `core/<block>`
 *   `core-navigation.css`  →  `core/navigation`
 *   `core-cover.css`       →  `core/cover`
 *
 * @since 0.3.0
 * @return void
 */
function blocklane_enqueue_block_styles(): void {
	// glob() returns `false` on a filesystem error (restricted hosts,
	// permission issues) — distinct from returning `array()` when the
	// directory is simply empty. `empty( false )` is true, so without
	// the is_array() guard a failed glob and "no files present" both
	// silently skip registration and look identical from the outside.
	$files = glob( get_theme_file_path( '/assets/styles/core-*.css' ) );
	if ( ! is_array( $files ) || empty( $files ) ) {
		return;
	}
	foreach ( $files as $file ) {
		$filename   = basename( $file, '.css' );
		$block_name = str_replace( 'core-', 'core/', $filename );
		wp_enqueue_block_style(
			$block_name,
			array(
				'handle' => "blocklane-block-{$filename}",
				'src'    => get_theme_file_uri( "assets/styles/{$filename}.css" ),
				'path'   => get_theme_file_path( "assets/styles/{$filename}.css" ),
				'ver'    => BLOCKLANE_VERSION,
			)
		);
	}
}
add_action( 'init', 'blocklane_enqueue_block_styles' );

/**
 * Front-end script for a Navigation block that opens a custom overlay: keeps
 * the overlay part's band lined up with the header (see
 * assets/js/navigation-overlay.js and the "Mobile overlay" rules in
 * assets/styles/core-navigation.css). Enqueued from the block's render pass
 * so it ships only on pages that actually have such a nav. On a block theme
 * the whole template renders before wp_head() (template-canvas.php), so the
 * tag prints in the head, deferred; a nav rendered later (a widget, an
 * embed) would print with the footer scripts — either way after the DOM the
 * script reads is parsed, which its readyState branch covers.
 *
 * @since 0.10.0
 * @param string $content The block's rendered markup.
 * @param array  $block   The parsed block.
 * @return string The markup, unchanged.
 */
function blocklane_enqueue_navigation_overlay_script( string $content, array $block ): string {
	if ( ! empty( $block['attrs']['overlay'] ) && ! is_admin() ) {
		wp_enqueue_script(
			'blocklane-navigation-overlay',
			get_theme_file_uri( 'assets/js/navigation-overlay.js' ),
			array(),
			BLOCKLANE_VERSION,
			array( 'strategy' => 'defer' )
		);
	}
	return $content;
}
add_filter( 'render_block_core/navigation', 'blocklane_enqueue_navigation_overlay_script', 10, 2 );

/**
 * Load core block CSS on demand instead of bundling every core block's
 * styles into one request. WordPress's default concatenates ~30+ core
 * block stylesheets into one blob served on every page load; flipping
 * this filter on makes WP enqueue only the CSS for blocks actually
 * rendered on the current page. Pairs with `blocklane_enqueue_block_styles`
 * above which does the same for our own variation CSS. Typical saving:
 * ~30 KB / page on a marketing landing page that doesn't use blocks
 * like gallery / audio / video / social-links / RSS / calendar.
 *
 * @since 0.3.0
 */
add_filter( 'should_load_separate_core_block_assets', '__return_true' );

/**
 * Disable WordPress's legacy emoji polyfill. The script, inline styles,
 * and s.w.org DNS prefetch that core injects into every `<head>` and
 * admin page exist to paper over missing native emoji glyphs on old
 * Android / IE — platforms the theme's 6.9 minimum already excludes.
 * Removing saves one HTTP request, a render-blocking inline script,
 * ~13 KB of bytes, and a stray DNS prefetch.
 *
 * @since 0.3.0
 * @return void
 */
function blocklane_disable_emoji(): void {
	remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
	remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
	remove_action( 'wp_print_styles', 'print_emoji_styles' );
	remove_action( 'admin_print_styles', 'print_emoji_styles' );
	remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
	remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );
	remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );
}
add_action( 'init', 'blocklane_disable_emoji' );
