<?php
/**
 * Mega Menu — fallback-mode stand-in loader.
 *
 * Blocklane Pro's mega menu already degrades on the FRONT of a
 * deactivated site (its saved markup is a core-navigation-shaped
 * submenu). This file completes the story in the EDITOR: while Pro is
 * inactive, the theme registers the block client-side as a read-only
 * stand-in — same metadata, same save, same deprecations, imported from
 * Pro's source at build time — so editors see an intentional navigation
 * item instead of core's "unsupported block" placeholder, and every Pro
 * attribute survives a re-save. Reactivating Blocklane Pro takes the
 * block over again and this enqueue becomes a no-op.
 *
 * Bundle: assets/js/mega-menu-fallback/ — GENERATED by the theme's own
 * toolchain (`npm run build` in themes/blocklane, from
 * src/mega-menu-fallback/) and never committed; the release zip carries
 * the built copy (bin/dist-check.php refuses a theme without it). A
 * checkout that has not built it gets a loud miss below, not silence.
 * See docs/safe-degradation.md.
 *
 * @package blocklane
 * @since   0.5.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Enqueue the stand-in editor script while Blocklane Pro is inactive.
 *
 * @since 0.5.0
 * @return void
 */
function blocklane_mega_menu_fallback_enqueue(): void {
	// Blocklane Pro registers the block server-side on init; when it has,
	// the real editor experience is in charge and the stand-in stays away.
	if ( WP_Block_Type_Registry::get_instance()->is_registered( 'blocklane-pro/mega-menu' ) ) {
		return;
	}

	// Safe mode silences every Blocklane surface, theme-side included.
	if ( defined( 'BLOCKLANE_PRO_SAFE_MODE' ) && BLOCKLANE_PRO_SAFE_MODE ) {
		return;
	}

	$asset_file = get_theme_file_path( 'assets/js/mega-menu-fallback/index.asset.php' );
	if ( ! file_exists( $asset_file ) ) {
		// The bundle is build output (untracked since #667): a checkout that has
		// not run the theme's build has no stand-in, and a silent return here
		// would be indistinguishable from "Pro is active". The warning is the
		// debug trail; the visible alarm is blocklane_mega_menu_fallback_check()
		// on admin_init, because this hook fires only on the block-editor
		// screens, where core CSS hides every legacy admin notice.
		wp_trigger_error( __FUNCTION__, 'The mega menu editor stand-in is not built: assets/js/mega-menu-fallback/index.asset.php is missing. Run `npm ci && npm run build` in themes/blocklane (a development checkout), or reinstall the theme from its release zip.', E_USER_WARNING );
		return;
	}
	$asset = include $asset_file;

	wp_enqueue_script(
		'blocklane-mega-menu-fallback',
		get_theme_file_uri( 'assets/js/mega-menu-fallback/index.js' ),
		$asset['dependencies'],
		$asset['version'],
		true
	);
}
add_action( 'enqueue_block_editor_assets', 'blocklane_mega_menu_fallback_enqueue' );

/**
 * The visible alarm for a missing stand-in bundle. Runs on admin_init —
 * every wp-admin request, after init has let Blocklane Pro register its
 * block — and hooks the notice for the screens that actually print legacy
 * admin notices (Dashboard, Plugins, Themes, …). The block-editor screens
 * hide them by core CSS, so hooking from the enqueue callback alone was a
 * notice nobody could see (#678).
 *
 * @since 0.9.0
 * @return void
 */
function blocklane_mega_menu_fallback_check(): void {
	if ( WP_Block_Type_Registry::get_instance()->is_registered( 'blocklane-pro/mega-menu' ) ) {
		return; // Pro is active: the stand-in is not needed.
	}
	if ( defined( 'BLOCKLANE_PRO_SAFE_MODE' ) && BLOCKLANE_PRO_SAFE_MODE ) {
		return;
	}
	if ( file_exists( get_theme_file_path( 'assets/js/mega-menu-fallback/index.asset.php' ) ) ) {
		return;
	}
	add_action( 'admin_notices', 'blocklane_mega_menu_fallback_missing_notice' );
}
add_action( 'admin_init', 'blocklane_mega_menu_fallback_check' );

/**
 * The admin notice for a missing stand-in bundle — shown to whoever can
 * act on it, on the admin screens that print notices.
 *
 * @since 0.9.0
 * @return void
 */
function blocklane_mega_menu_fallback_missing_notice(): void {
	if ( ! current_user_can( 'switch_themes' ) ) {
		return;
	}
	printf(
		'<div class="notice notice-warning"><p>%s</p></div>',
		esc_html__( 'Blocklane: the mega menu editor stand-in is not built (assets/js/mega-menu-fallback is missing). On a development checkout run `npm ci && npm run build` in the theme; on a live site reinstall the theme from its release zip.', 'blocklane' )
	);
}
